project:
  type: website
  output-dir: docs
  resources: 
   - "_lectures"
   - "_homeworks"
   - "_syllabus"

website:
  title: "Structural Equation Modeling Fall 2025 (PSQF 6249)"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual
 