---
title: "Structural Equation Modeling (Fall 2025; University of Iowa: PSQF 6249)"
---

## Course Objectives

The course objective is for participants to be able to understand and implement contemporary approaches to structural equation modeling including the use and application of measurement models for latent traits (i.e., confirmatory factor models, item response models). In addition to these statistical models, the course will also focus on the statistical concepts behind these models and how they relate to each other with respect to scale construction, evaluation, and the use of variables with measurement error in analyses.

Participants should already be comfortable with general linear models (e.g., regression, ANOVA), which can be reviewed using the [PSQF 6243 (Intermediate Statistical Methods) materials](http://lesahoffman.com/PSQF6243/index.html). Ideally participants should also be familiar with generalized linear models (e.g., logistic regression, count regression), which can be reviewed using the [PSQF 6270 (Generalized Linear Models) materials](http://lesahoffman.com/PSQF6270/index.html).

Class time will be devoted primarily to lectures, examples, and spontaneous review, the materials for which will be available for download at the course website. Readings and other resources have been suggested for each topic and may be updated later. Video recordings of each class will be made available on YouTube so that closed captioning will be provided, and supplemental videos for specific topics (e.g., software demos) may be added as well. Auditors and visitors are always welcome to attend class. No required class sessions will be held outside the regular class time given above (i.e., no additional midterm or final exam sessions). However, because the course will have an applied focus requiring the use of statistical software, participants are encouraged to attend group-based office hours (via zoom only), in which multiple participants can receive immediate assistance simultaneously or sequentially.

Note: The materials in this course were created by both myself and [Lesa Hoffman](https://www.lesahoffman.com) through years of collaboration. Materials created by Lesa are used with her permission.

## Course Readings

The course will provide all readings on our course ICON site.

## Course Details

+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Instructor:              | Jonathan Templin                                                                                                                                                        |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| email:                   | [jonathan-templin\@uiowa.edu](mailto:jonathan-templin@uiowa.edu)                                                                                                        |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Course website:          | <https://jonathantemplin.github.io/Structural-Equation-Modeling-Fall-2025/>                                                                                             |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Course repo:             | <https://github.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025>                                                                                             |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Course YouTube Playlist: | <https://www.youtube.com/playlist?list=PLSmMs4UgmSMhOnAG5GAPutNmlpcIhEmmZ>                                                                                              |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Course IDAS Site:        | <https://notebooks.hpc.uiowa.edu/fall2025-psqf-6249-0001/hub/home>                                                                                                      |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Office:                  | S300A Lindquist Center                                                                                                                                                  |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Office Phone:            | 319-335-6429                                                                                                                                                            |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Classroom:               | 60 SH                                                                                                                                                                   |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Course Meeting Time:     | W 12:30pm-3:20pm                                                                                                                                                        |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Instructor Office Hours: | M 1:30pm-3:30pm via Zoom at <https://uiowa.zoom.us/my/jonathantemplinuiowa>                                                                                             |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Syllabus:                | <https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/main/_syllabus/psqf6429f2025_syllabus.pdf> |
+--------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

## Current Homework Assignments

| Assignment                    | Due Date         |
|-------------------------------|------------------|
| Homework #4: IRT on your data | December 1, 2025 |

## Lecture and Class Files and Links

```{=html}
<style>
table {
  border-collapse: collapse;
  width: 100%;
  border: 1px solid #ddd;
}

th, td {
  text-align: left;
  padding: 16px;
}
</style>
```

+-----------+-----------------------------------------------------------------------+:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| # Date    | # Topic                                                               | # Readings/Materials                                                                                                                                                                                                                    |
+-----------+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 27 Aug    | Introduction to Course/Latent Trait Measurement Models                | **Readings**                                                                                                                                                                                                                            |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   **Required:** Brown (2015) Chs. 1 and 2                                                                                                                                                                                             |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   **Optional:** John & Benet-Martinez (2014), Preacher & McCollum (2003)                                                                                                                                                              |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | <hr>                                                                                                                                                                                                                                    |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | \                                                                                                                                                                                                                                       |
|           |                                                                       | **Materials**                                                                                                                                                                                                                           |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Syllabus](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/main/_syllabus/psqf6429f2025_syllabus.pdf)                                                   |
|           |                                                                       | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/main/_lectures/01_Introduction/psqf6249f2025_lecture01.pdf)                            |
|           |                                                                       | -   [R syntax](https://github.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/blob/main/_lectures/01_Introduction/psqf6249f2025_lecture01.R)                                                                                 |
|           |                                                                       | -   [Lecture Video (available after class)](https://youtu.be/hTDtAkumn4s)                                                                                                                                                               |
+-----------+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10 Sep    | Classical Test Theory/Exploratory Factor Analysis                     | NOTE: No in-person class\                                                                                                                                                                                                               |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | <hr>                                                                                                                                                                                                                                    |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | \                                                                                                                                                                                                                                       |
|           |                                                                       | **Readings**                                                                                                                                                                                                                            |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   **Required:** McDonald (1999), Ch. 5                                                                                                                                                                                                |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   **Optional:** Clifton (2020), McNeish (2018)                                                                                                                                                                                        |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | <hr>                                                                                                                                                                                                                                    |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Materials**                                                                                                                                                                                                                           |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   Classical Test Theory (from Lesa Hoffman's Spring 2024 version of this course):                                                                                                                                                     |
|           |                                                                       |     -   [Lecture Slides](https://www.lesahoffman.com/PSQF6249/PSQF6249_Lecture3_CTT_Reliability.pdf)                                                                                                                                    |
|           |                                                                       |     -   [Example](https://www.lesahoffman.com/PSQF6249/PSQF6249_Example3_CTT_Reliability.pdf)                                                                                                                                           |
|           |                                                                       |     -   Videos:                                                                                                                                                                                                                         |
|           |                                                                       |         -   [Part 1: Lecture 3](https://youtu.be/GfokvpnjIQY)                                                                                                                                                                           |
|           |                                                                       |         -   [Part 2: Lecture 3](https://youtu.be/Ni8qKh4XlsY)                                                                                                                                                                           |
|           |                                                                       |         -   [Part 3: Example 3](https://youtu.be/t2LPiN6Tp7s)                                                                                                                                                                           |
|           |                                                                       | -   Exploratory Factor Analysis (from a Multivariate Statistics course I taught in 2016)                                                                                                                                                |
|           |                                                                       |     -   [Lecture Slides](https://jonathantemplin.com/wp-content/uploads/2018/04/mv16epsy905_lecture13.pdf)                                                                                                                              |
|           |                                                                       |     -   R Files:                                                                                                                                                                                                                        |
|           |                                                                       |         -   [Example Data (part 1)](https://jonathantemplin.com/wp-content/uploads/2018/04/mv16epsy905_lecture13a.csv)                                                                                                                  |
|           |                                                                       |         -   [Example Data (part 2)](https://jonathantemplin.com/wp-content/uploads/2018/04/mv16epsy905_lecture13b.csv)                                                                                                                  |
|           |                                                                       |         -   [Syntax](https://jonathantemplin.com/wp-content/uploads/2018/04/mv16epsy905_lecture13.r)                                                                                                                                    |
|           |                                                                       |         -   [R Markdown](https://jonathantemplin.com/wp-content/uploads/2018/04/mv16epsy905_lecture13.html)                                                                                                                             |
|           |                                                                       |     -   Videos:                                                                                                                                                                                                                         |
|           |                                                                       |         -   [Part 1](https://youtu.be/vFktlubZ9i8)                                                                                                                                                                                      |
|           |                                                                       |         -   [Part 2](https://youtu.be/SW-UzbOdfks)                                                                                                                                                                                      |
+-----------+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 03 Sep\   | Path Analysis                                                         | **Readings**                                                                                                                                                                                                                            |
| 17 Sep    |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   **Required:** Kaplan (2008) Ch. 2                                                                                                                                                                                                   |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   **Optional:** None                                                                                                                                                                                                                  |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | <hr>                                                                                                                                                                                                                                    |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Materials**                                                                                                                                                                                                                           |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/main/_lectures/02_Path_Analysis/psqf6249f2025_lecture02.pdf)                           |
|           |                                                                       | -   [R syntax](https://github.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/blob/main/_lectures/02_Path_Analysis/psqf6249f2025_lecture02.R)                                                                                |
|           |                                                                       | -   [Example Data](https://github.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/blob/main/_lectures/02_Path_Analysis/mathdata.csv)                                                                                         |
|           |                                                                       | -   [Lecture Video](https://youtu.be/sH7V9PrCs7U) (September 3)                                                                                                                                                                         |
|           |                                                                       | -   [Lecture Video](https://youtu.be/SekW6__MNSE) (September 17)                                                                                                                                                                        |
|           |                                                                       | -   [Lecture Video](https://youtu.be/68X7scAOkaA) (September 24)                                                                                                                                                                        |
+-----------+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 24 Sep\   | Confirmatory Factor Analysis                                          | **Readings**                                                                                                                                                                                                                            |
| 01 Oct\   |                                                                       |                                                                                                                                                                                                                                         |
| 08 Oct\   |                                                                       | -   **Required:**                                                                                                                                                                                                                       |
| 15 Oct    |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   Brown (2015) Ch. 3 (September 24)                                                                                                                                                                                               |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   Brown (2015) Ch. 4 (October 1)                                                                                                                                                                                                  |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   Brown (2015) Ch. 5 (October 8)                                                                                                                                                                                                  |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   **Optional:**                                                                                                                                                                                                                       |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   Clifton (2020; September 24)                                                                                                                                                                                                    |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   Ferrando (2009; October 1)                                                                                                                                                                                                      |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   West et al. (2023; October 1)                                                                                                                                                                                                   |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   McNeish & Wolf (2020; October 8)                                                                                                                                                                                                |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   Bollen & Diamantopoulos (2017; October 8)                                                                                                                                                                                       |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   Enders (2010, Chs. 3-5; October 8)                                                                                                                                                                                              |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | <hr>                                                                                                                                                                                                                                    |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Materials**                                                                                                                                                                                                                           |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/main/_lectures/03_Confirmatory_Factor_Analysis/psqf6249f2025_lecture03.pdf)            |
|           |                                                                       | -   [lavaan Example (real data not provided)](https://jonathantemplin.github.io/Structural-Equation-Modeling-Fall-2025/_lectures/03_Confirmatory_Factor_Analysis/PSQF6249_Example04_CFA_lavaan.html)                                    |
|           |                                                                       |     -   [Real Data RMD file](https://github.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/blob/main/_lectures/03_Confirmatory_Factor_Analysis/PSQF6249_Example04_CFA_lavaan.Rmd) (will not run)                            |
|           |                                                                       |     -   [Simulated Data RMD file](https://github.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/blob/main/_lectures/03_Confirmatory_Factor_Analysis/PSQF6249_Example04_CFA_simulated_lavaan.Rmd) (will run on your machine) |
|           |                                                                       | -   Lecture Video from September 24: Not available                                                                                                                                                                                      |
|           |                                                                       | -   [Lecture Video](https://youtu.be/3Ldf8VE3zGk) (October 1)                                                                                                                                                                           |
|           |                                                                       | -   [Lecture Video](https://youtu.be/ET7XabdXG1E) (October 8)                                                                                                                                                                           |
|           |                                                                       | -   [Lecture Video](https://youtu.be/rTGz36BulDo) (October 15)                                                                                                                                                                          |
+-----------+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 08 Oct    | Homework #2 and Midterm Discussion                                    | -   [Lecture Video](https://youtu.be/KD1xPC00UTY) (October 8)                                                                                                                                                                           |
+-----------+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 22 Oct    | Binary Item Response Theory                                           | Note: No in-person class October 22                                                                                                                                                                                                     |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Readings**                                                                                                                                                                                                                            |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   **Required:**                                                                                                                                                                                                                       |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   Embretson and Reise (2000) Chs. 5                                                                                                                                                                                               |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   **Optional**                                                                                                                                                                                                                        |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   Maydeu-Olivares (2015)                                                                                                                                                                                                          |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   Paek et al. (2018)                                                                                                                                                                                                              |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | <hr>                                                                                                                                                                                                                                    |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Binary Data Materials**                                                                                                                                                                                                               |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Lecture Slides (part A)](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/main/_lectures/04_Item_Response_Theory/psqf6249f2025_lecture04a.pdf)          |
|           |                                                                       | -   [Lecture Slides (part B)](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/main/_lectures/04_Item_Response_Theory/psqf6249f2025_lecture04b.pdf)          |
|           |                                                                       | -   lavaan and mirt Example (real data not provided)                                                                                                                                                                                    |
|           |                                                                       |     -   [Markdown File](https://github.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/blob/main/_lectures/04_Item_Response_Theory/psqf6249f2025_example04.Rmd)                                                              |
|           |                                                                       |     -   [HTML File](https://jonathantemplin.github.io/Structural-Equation-Modeling-Fall-2025/_lectures/04_Item_Response_Theory/psqf6249f2025_example04.nb.html)                                                                         |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Lecture Videos from Lesa Hoffman (used with permission)**                                                                                                                                                                             |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Video Part 1:](https://youtu.be/Sa763fBFXLQ) Lecture 4a slides 1-20                                                                                                                                                                |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Video Part 2:](https://youtu.be/rG-AV5kYm0U) Lecture 4a (slides 16-37)                                                                                                                                                             |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Video Part 3:](https://youtu.be/eh4jp5xb0Ms) Lecture 4a (slides 38-56)                                                                                                                                                             |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | <hr>                                                                                                                                                                                                                                    |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Video Part 1:](https://youtu.be/JHVRMoNx-u8) Lecture 4b (slides 1-9)                                                                                                                                                               |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Video Part 2:](https://youtu.be/qTMN2L51D_A) Lecture 5b (slides 4-30)                                                                                                                                                              |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Video Part 3:](https://youtu.be/K45I9KOJuPM?si=f08PAoIZ69y8XPNW&t=897) Lecture 5b (slides 25-31)                                                                                                                                   |
+-----------+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 05 Nov    | Polytomous Item Response Theory                                       | **Readings**                                                                                                                                                                                                                            |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   **Required:**                                                                                                                                                                                                                       |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   Embretson and Reise (2000) Ch. 5                                                                                                                                                                                                |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Lecture Materials**                                                                                                                                                                                                                   |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Lecture Slides (part C)](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/main/_lectures/04_Item_Response_Theory/psqf6249f2025_lecture04c.pdf)          |
|           |                                                                       | -   lavaan and mirt Example (real data not provided)                                                                                                                                                                                    |
|           |                                                                       |     -   [Markdown File](https://github.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/blob/main/_lectures/04_Item_Response_Theory/psqf6249f2025_example04b.Rmd)                                                             |
|           |                                                                       |     -   [HTML File](https://jonathantemplin.github.io/Structural-Equation-Modeling-Fall-2025/_lectures/04_Item_Response_Theory/psqf6249f2025_example04b.nb.html)                                                                        |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Lecture Videos**                                                                                                                                                                                                                      |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Video:](https://youtu.be/Mv98avb07QQ) IRT (abbreviated) as a measurement model for categorical data                                                                                                                                |
+-----------+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12 Nov    | Diagnostic Models (guest Lecture) and Higher Order and Method Factors | **Diagnostic Classification Models**                                                                                                                                                                                                    |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Lecture Materials:**                                                                                                                                                                                                                  |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/main/_lectures/05_Higher_Order_and_Method_Factors/psqf62492025_DCMs.pdf)               |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Higher Order and Method Factors**                                                                                                                                                                                                     |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Readings:**                                                                                                                                                                                                                           |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   Brown (2015), Chapter 6                                                                                                                                                                                                             |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Lecture Materials:**                                                                                                                                                                                                                  |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/main/_lectures/05_Higher_Order_and_Method_Factors/psqf6249f2025_lecture05.pdf)         |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   lavaan example (real data not provided)                                                                                                                                                                                             |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   [Markdown File](https://github.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/blob/main/_lectures/05_Higher_Order_and_Method_Factors/psqf6249f2025_example05.Rmd)                                                   |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   [HTML File](https://jonathantemplin.github.io/Structural-Equation-Modeling-Fall-2025/_lectures/05_Higher_Order_and_Method_Factors/psqf6249f2025_example05.html)                                                                 |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Lecture Video:**                                                                                                                                                                                                                      |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Lecture Video](https://youtu.be/TLKtAMQTADI)                                                                                                                                                                                       |
+-----------+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 19 Nov    | Measurement Invariance (Differential Item Functioning)                | **Readings:**                                                                                                                                                                                                                           |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   Vandenberg & Lance (2000)                                                                                                                                                                                                           |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   Brown (2015), Ch. 7                                                                                                                                                                                                                 |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Lecture Materials:**                                                                                                                                                                                                                  |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Lecture Slides](https://docs.google.com/viewer?url=https://raw.githubusercontent.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/main/_lectures/06_Measurement_Invariance/psqf6249f2025_lecture06.pdf)                  |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   lavaan example (real data not provided)                                                                                                                                                                                             |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   [Markdown File](https://github.com/jonathantemplin/Structural-Equation-Modeling-Fall-2025/blob/main/_lectures/06_Measurement_Invariance/psqf6249f2025_example06.Rmd)                                                            |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       |     -   [HTML File](https://jonathantemplin.github.io/Structural-Equation-Modeling-Fall-2025/_lectures/06_Measurement_Invariance/psqf6249f2025_example06.html)                                                                          |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | **Lecture Video:**                                                                                                                                                                                                                      |
|           |                                                                       |                                                                                                                                                                                                                                         |
|           |                                                                       | -   [Lecture Video](https://youtu.be/rtcTy_SqH3A)                                                                                                                                                                                       |
+-----------+-----------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
